### ISSUE TITLE
Join the upstream maintenance team?

### ISSUE THREAD

**Issue by azmeuk** [JuliusPC/OpenID-Connect-PHP#22]
Hi @JuliusPC 
The maintainer of the upstream [is OK to give write access to volunteers](https://github.com/jumbojett/OpenID-Connect-PHP/issues/270). Given the activity of your fork, I think it would make sense for you to join the team. Would you be interested? If so, I think you can just say a word there.

I am not sure the original author gets GH notifications, but I will write him an email then.

What do you think?

**Comment by JuliusPC** [comment]
Hi,

thanks for the reminder.

For a bunch of reasons I decided to maintain my own version and I keep that for now. Version 2 might introduce some major improvements / changes.

**Comment by azmeuk** [comment]
Ok this is too bad, but I understand that working on the upstream might be pointless in your situation, with your fork having a lot diverged now.
If you ever change your mind, I would be ok to give a hand for bringing your changes upstream.
